export type Lang = "id" | "en";

export const content = {
  id: {
    langLabel: "ID",
    role: "Web Developer Portfolio",
    heroKicker: "Web Developer & Digital Marketing Specialist",
    heroLine: "Developer yang memahami bisnis, marketing, dan kebutuhan pengguna.",
    seeMore: "Lihat Selengkapnya",
    heroStats: [
      { value: "4+", label: "Tahun Pengalaman" },
      { value: "6", label: "Proyek Kerjaan" },
      { value: "14", label: "Proyek Pribadi" },
      { value: "13", label: "Brand F&B" },
    ],
    tags: [
      "#Web_Development",
      "#PHP",
      "#CRM",
      "#Sistem_Internal",
      "#Landing_Page",
      "#API_Integration",
      "#Digital_Marketing",
      "#Content_Strategy",
      "#Social_Media",
      "#Copywriting",
    ],
    nav: { about: "Tentang", resume: "Resume", work: "Proyek" },
    hello: "Halo,",
    myName: ["Nama saya", "Angger"],
    photoCaption:
      "Dari strategi konten ke sistem yang benar-benar dipakai - solusi digital yang efektif untuk kebutuhan bisnis.",
    introduction: "Perkenalan",
    introTitle: "Web Developer & Digital Marketing Specialist",
    introBody: [
      "Profesional di bidang Web Development dan Digital Marketing dengan pengalaman dalam pengembangan sistem berbasis web, CRM, sistem internal perusahaan, integrasi antarplatform, serta pengelolaan media sosial dan strategi konten.",
      "Berpengalaman mengembangkan solusi digital untuk mendukung kebutuhan operasional dan bisnis perusahaan, sekaligus memiliki pengalaman dalam perencanaan konten, riset tren, copywriting, analisis performa, dan strategi pertumbuhan media sosial.",
    ],
    getInTouch: "Hubungi Saya",
    getInTouchBody:
      "Punya proyek, lowongan, atau sekadar mau ngobrol? Saya fast response di semua channel.",
    contactEmailCta: "Kirim Email",
    contactWhatsappCta: "Fast Response",
    contact: {
      email: "anggerajiprayogokusuma@gmail.com",
      emailLabel: "Email",
      linkedin: "anggeraji",
      linkedinLabel: "LinkedIn",
      linkedinUrl: "https://www.linkedin.com/in/anggeraji",
      github: "siinmedia",
      githubLabel: "GitHub",
      githubUrl: "https://github.com/siinmedia",
      whatsapp: "6285155145788",
      whatsappLabel: "WhatsApp",
      whatsappUrl: "https://wa.me/6285155145788",
      city: "Jepara",
    },
    experience: "Pengalaman Kerja",
    expertise: "Keahlian",
    expertiseBody:
      "Web Development, CRM, Sistem Internal, API & System Integration, Digital Marketing, Content Strategy, Social Media Management",
    hardskill: "Hardskill",
    marketing: "Digital Marketing",
    softskill: "Softskill",
    education: "Pendidikan",
    graduated: "Lulus 2022",
    school: "SMK Hasan Kafrawi",
    schoolCity: "Mayong, Jepara, Jawa Tengah",
    extra: "Informasi Tambahan",
    languagesLabel: "Bahasa",
    languagesValue: "Bahasa Indonesia · Bahasa Inggris",
    focusLabel: "Fokus",
    focusValue:
      "Web Development · Programming · CRM · Digital Marketing · Social Media · Content Strategy",
    workTitle: "Proyek Terpilih",
    workSubtitle: "Sistem dan produk digital yang dikembangkan untuk kebutuhan bisnis nyata.",
    impactKicker: "Dampak",
    impactTitle: "Angka yang Bicara",
    impactBody:
      "Hasil terukur dari sistem internal dan strategi konten yang saya bangun.",
    impactStats: [
      { value: "30K+", label: "Follower baru dalam 1 bulan" },
      { value: "8Jt", label: "Peak views per bulan" },
      { value: "376", label: "Item inventaris dikelola" },
      { value: "60+", label: "Konten terjadwal per bulan" },
    ],
    ctaKicker: "Kolaborasi",
    ctaTitle: "Mari Bekerja Sama",
    ctaBody:
      "Punya proyek, butuh sistem internal, atau mau mengembangkan brand? Ceritakan kebutuhanmu - saya bantu wujudkan.",
    ctaWhatsapp: "Chat WhatsApp",
    ctaEmail: "Kirim Email",
    ctaDownload: "Download CV",
    present: "Sekarang",
    jobs: [
      {
        period: "Des 2025 - Sekarang",
        role: "PHP Web Developer",
        company: "Stealth Company",
        bullets: [
          "Membangun CRM Leads - dari flow lead hingga handle customer, lengkap dengan data analisis - dalam 1 bulan.",
          "Membangun sistem inventaris dalam 6 minggu: mengelola 376 item + sub item dan mendukung proses stock opname.",
          "Membangun sistem perencanaan konten dalam 2 minggu dengan flow multi-role & multi-account serta data analisis lengkap.",
          "Membangun HRIS KPI dalam 4 minggu: flow HR, absensi, dan payroll dengan notifikasi email + setup Meta WABA.",
          "Mengembangkan 5+ landing page untuk kebutuhan perusahaan dan brand yang fokus pada konversi.",
          "Melakukan integrasi antarplatform (WhatsApp/Meta WABA, QRIS/payment, API scraping) untuk otomatisasi alur kerja.",
          "Menjaga uptime sistem di atas 99% melalui troubleshooting, pemeliharaan, dan pengembangan fitur rutin.",
          "Memberikan dukungan teknis dan IT untuk 10+ pengguna aktif di seluruh sistem.",
        ],
        footerLabel: "Sistem",
        footerItems: ["CRM Leads", "Sistem Inventaris Internal", "Sistem Perencanaan Konten", "HRIS KPI"],
      },
      {
        period: "Nov 2022 - Des 2025",
        role: "Social Media Marketing Specialist",
        company: "Stealth Company",
        bullets: [
          "Menyusun strategi dan perencanaan konten untuk 13 brand F&B yang dikelola.",
          "Mengelola kalender konten dengan rata-rata 60+ konten terjadwal per bulan lintas platform.",
          "Melakukan riset tren media sosial 4+ kali per bulan untuk menjaga relevansi konten dengan audiens.",
          "Menulis 60+ copywriting per bulan untuk caption, promosi, dan komunikasi digital brand.",
          "Menganalisis performa 200+ konten per tahun dan menjadikan data sebagai dasar penyusunan strategi.",
          "Menjalankan organic growth yang mencapai 30.000 follower baru dalam satu bulan.",
          "Mencapai peak view hingga 8 juta per bulan pada konten yang dikelola.",
          "Mengelola media sosial 5 brand utama secara aktif (Be Nice Coffee, Esteh Ibukota, Kentang Ganteng, Raja Steak, MyBestea).",
        ],
        footerLabel: "Brand",
        footerItems: [
          "Be Nice Coffee",
          "Esteh Ibukota",
          "Kentang Ganteng",
          "Raja Steak",
          "MyBestea",
        ],
      },
    ],
    projects: [
      {
        index: "01",
        title: "CRM Leads Management",
        summary: "Sistem manajemen leads dengan flow hingga handle customer.",
        bullets: [
          "CRM Leads dengan flow lengkap dari lead hingga handle customer.",
          "Data analisis untuk memantau performa leads dan kebutuhan operasional.",
          "Pengembangan fitur berdasarkan kebutuhan dan alur bisnis.",
        ],
        stack: ["PHP", "Database", "CRM Leads"],
      },
      {
        index: "02",
        title: "Sistem Inventaris Internal",
        summary: "Digitalisasi pencatatan dan pengelolaan 376 item inventaris.",
        bullets: [
          "Dibangun dalam 6 minggu: mengelola 376 item + sub item.",
          "Mendukung proses stock opname dan pengelolaan data inventaris perusahaan.",
        ],
        stack: ["PHP", "Database"],
      },
      {
        index: "03",
        title: "Sistem Perencanaan Konten",
        summary: "Alat internal untuk kalender konten multi-role & multi-account.",
        bullets: [
          "Dibangun dalam 2 minggu dengan flow multi-role dan multi-account.",
          "Data analisis lengkap untuk memantau performa konten.",
        ],
        stack: ["PHP", "Workflow"],
      },
      {
        index: "04",
        title: "Website & Landing Page",
        summary: "Halaman yang menggabungkan kebutuhan teknis dan tujuan pemasaran.",
        bullets: [
          "Pengembangan website dan landing page untuk kebutuhan bisnis dan pemasaran.",
          "Menggabungkan kebutuhan teknis dengan tujuan pemasaran dan komunikasi brand.",
        ],
        stack: ["HTML & CSS", "JavaScript", "SEO"],
      },
      {
        index: "05",
        title: "TernoAE",
        summary: "Platform ride-hailing lokal dengan sistem booking dan pelacakan real-time.",
        bullets: [
          "Platform ride-hailing lokal dengan booking dan pelacakan real-time.",
          "Web app untuk kebutuhan transportasi dengan fokus pengalaman pengguna.",
        ],
        stack: ["PHP", "Web App", "Transportation"],
        url: "https://ternoae.web.id",
        cta: "Lihat Live",
      },
      {
        index: "06",
        title: "QRIS Dynamic API",
        summary: "REST API untuk generate QRIS dinamis dari kode statis dengan nominal yang bisa diatur.",
        bullets: [
          "Endpoint POST JSON - kirim QRIS statis + nominal, terima QRIS dinamis siap scan.",
          "Digunakan untuk integrasi pembayaran, donasi, atau top-up pada sistem internal.",
        ],
        stack: ["REST API", "JSON", "QRIS"],
        url: "/api-docs",
        internal: true,
        cta: "Buka API Docs",
      },
      {
        index: "07",
        title: "Platform Analitik Konten",
        summary: "Web SaaS analitik konten untuk memantau performa postingan lintas platform.",
        bullets: [
          "Dashboard analitik konten: views, engagement, like, komentar lintas platform.",
          "Memantau performa konten sebagai dasar strategi organik yang terukur.",
        ],
        stack: ["Web App", "Analytics", "SaaS"],
        url: "https://demo.kasihkreasi.web.id/login",
        cta: "Lihat Demo",
        sourceUrl: "https://github.com/siinmedia/analisakonten",
        sourceLabel: "Source",
      },
    ],
    hardskills: [
      "PHP",
      "HTML & CSS",
      "JavaScript",
      "Pengembangan CRM",
      "Sistem Internal",
      "Database Management",
      "API & System Integration",
      "Troubleshooting & Maintenance",
    ],
    marketingSkills: [
      "Social Media Management",
      "Content Planning",
      "Content Strategy",
      "Copywriting",
      "Trend Research",
      "Social Media Analytics",
      "Organic Growth Strategy",
    ],
    softskills: [
      "Analisis Kebutuhan Bisnis",
      "Problem Solving",
      "System Analysis",
      "Project Management",
      "Business Process Analysis",
    ],
  },

  en: {
    langLabel: "EN",
    role: "Web Developer Portfolio",
    heroKicker: "Web Developer & Digital Marketing Specialist",
    heroLine: "A developer who understands business, marketing, and user needs.",
    seeMore: "See More",
    heroStats: [
      { value: "4+", label: "Years Experience" },
      { value: "6", label: "Work Projects" },
      { value: "14", label: "Personal Projects" },
      { value: "13", label: "F&B Brands" },
    ],
    tags: [
      "#Web_Development",
      "#PHP",
      "#CRM",
      "#Internal_Systems",
      "#Landing_Page",
      "#API_Integration",
      "#Digital_Marketing",
      "#Content_Strategy",
      "#Social_Media",
      "#Copywriting",
    ],
    nav: { about: "About me", resume: "Resume", work: "Work" },
    hello: "Hello,",
    myName: ["My name", "is Angger"],
    photoCaption:
      "From content strategy to systems people actually use - effective digital solutions for real business needs.",
    introduction: "Introduction",
    introTitle: "Web Developer & Digital Marketing Specialist",
    introBody: [
      "A professional in Web Development and Digital Marketing with experience building web-based systems, CRM, internal company systems, cross-platform integrations, as well as social media management and content strategy.",
      "Experienced in developing digital solutions that support business and operational needs, combined with a background in content planning, trend research, copywriting, performance analysis, and social media growth strategy.",
    ],
    getInTouch: "Get In Touch",
    getInTouchBody:
      "Have a project, a vacancy, or just want to chat? I reply fast on all channels.",
    contactEmailCta: "Send Email",
    contactWhatsappCta: "Fast Response",
    contact: {
      email: "anggerajiprayogokusuma@gmail.com",
      emailLabel: "Email",
      linkedin: "anggeraji",
      linkedinLabel: "LinkedIn",
      linkedinUrl: "https://www.linkedin.com/in/anggeraji",
      github: "siinmedia",
      githubLabel: "GitHub",
      githubUrl: "https://github.com/siinmedia",
      whatsapp: "6285155145788",
      whatsappLabel: "WhatsApp",
      whatsappUrl: "https://wa.me/6285155145788",
      city: "Jepara",
    },
    experience: "Experience",
    expertise: "Expertise",
    expertiseBody:
      "Web Development, CRM, Internal Systems, API & System Integration, Digital Marketing, Content Strategy, Social Media Management",
    hardskill: "Hard Skills",
    marketing: "Digital Marketing",
    softskill: "Soft Skills",
    education: "Education",
    graduated: "Class of 2022",
    school: "SMK Hasan Kafrawi",
    schoolCity: "Mayong, Jepara, Central Java",
    extra: "Additional Information",
    languagesLabel: "Languages",
    languagesValue: "Indonesian · English",
    focusLabel: "Focus",
    focusValue:
      "Web Development · Programming · CRM · Digital Marketing · Social Media · Content Strategy",
    workTitle: "Selected Work",
    workSubtitle: "Systems and digital products built for real business needs.",
    impactKicker: "Impact",
    impactTitle: "Numbers That Speak",
    impactBody:
      "Measurable results from the internal systems and content strategies I built.",
    impactStats: [
      { value: "30K+", label: "New followers in one month" },
      { value: "8M", label: "Peak views per month" },
      { value: "376", label: "Inventory items managed" },
      { value: "60+", label: "Scheduled posts per month" },
    ],
    ctaKicker: "Collaboration",
    ctaTitle: "Let's Work Together",
    ctaBody:
      "Have a project, need an internal system, or want to grow a brand? Tell me what you need - I'll help you build it.",
    ctaWhatsapp: "Chat on WhatsApp",
    ctaEmail: "Send Email",
    ctaDownload: "Download CV",
    present: "Present",
    jobs: [
      {
        period: "Dec 2025 - Present",
        role: "PHP Web Developer",
        company: "Stealth Company",
        bullets: [
          "Built a CRM Leads system - from lead flow to customer handling with data analytics - in 1 month.",
          "Built the inventory system in 6 weeks: managing 376 items + sub-items and supporting stock opname.",
          "Built the content planning system in 2 weeks with multi-role & multi-account flows plus full data analytics.",
          "Built an HRIS KPI system in 4 weeks: HR, attendance, and payroll flows with email notifications + Meta WABA setup.",
          "Developed 5+ landing pages for company and brand needs, focused on conversion.",
          "Integrated cross-platform systems (WhatsApp/Meta WABA, QRIS/payment, scraping API) to automate workflows.",
          "Kept system uptime above 99% through troubleshooting, maintenance, and ongoing feature work.",
          "Provided technical and IT support for 10+ active users across all systems.",
        ],
        footerLabel: "Systems",
        footerItems: ["CRM Leads", "Internal Inventory System", "Content Planning System", "HRIS KPI"],
      },
      {
        period: "Nov 2022 - Dec 2025",
        role: "Social Media Marketing Specialist",
        company: "Stealth Company",
        bullets: [
          "Developed content strategy and planning across 13 F&B brands.",
          "Managed the content calendar with an average of 60+ scheduled posts per month across platforms.",
          "Ran social media trend research 4+ times per month to keep content relevant to the audience.",
          "Wrote 60+ pieces of copy per month for captions, promotions, and digital brand communication.",
          "Analysed 200+ pieces of content per year and used the data to shape the next strategy.",
          "Ran organic growth that gained 30,000 new followers in a single month.",
          "Reached peak views of up to 8 million per month across managed content.",
          "Actively managed social media for 5 core brands (Be Nice Coffee, Esteh Ibukota, Kentang Ganteng, Raja Steak, MyBestea).",
        ],
        footerLabel: "Brands",
        footerItems: [
          "Be Nice Coffee",
          "Esteh Ibukota",
          "Kentang Ganteng",
          "Raja Steak",
          "MyBestea",
        ],
      },
    ],
    projects: [
      {
        index: "01",
        title: "CRM Leads Management",
        summary: "A leads management system with workflow through customer handling.",
        bullets: [
          "CRM Leads with a complete flow from lead to customer handling.",
          "Data analytics to monitor leads performance and operational needs.",
          "Features developed around real business needs and workflows.",
        ],
        stack: ["PHP", "Database", "CRM Leads"],
      },
      {
        index: "02",
        title: "Internal Inventory System",
        summary: "Digitised inventory recording and management of 376 items.",
        bullets: [
          "Built in 6 weeks: managing 376 items + sub-items.",
          "Supported stock opname and company inventory data management.",
        ],
        stack: ["PHP", "Database"],
      },
      {
        index: "03",
        title: "Content Planning System",
        summary: "An internal tool for multi-role & multi-account content calendars and workflows.",
        bullets: [
          "Built in 2 weeks with multi-role and multi-account workflows.",
          "Full data analytics for tracking content performance.",
        ],
        stack: ["PHP", "Workflow"],
      },
      {
        index: "04",
        title: "Website & Landing Page",
        summary: "Pages that combine technical needs with marketing goals.",
        bullets: [
          "Developed websites and landing pages for business and marketing needs.",
          "Combined technical requirements with marketing and brand communication goals.",
        ],
        stack: ["HTML & CSS", "JavaScript", "SEO"],
      },
      {
        index: "05",
        title: "TernoAE",
        summary: "Local ride-hailing platform with real-time booking and tracking system.",
        bullets: [
          "Local ride-hailing platform with real-time booking and tracking.",
          "Web app built for transportation, focused on user experience.",
        ],
        stack: ["PHP", "Web App", "Transportation"],
        url: "https://ternoae.web.id",
        cta: "View Live",
      },
      {
        index: "06",
        title: "QRIS Dynamic API",
        summary: "REST API to generate dynamic QRIS from a static code with customizable amount.",
        bullets: [
          "JSON POST endpoint - send static QRIS + amount, get a ready-to-scan dynamic QRIS.",
          "Used for payment, donation, or top-up integrations across internal systems.",
        ],
        stack: ["REST API", "JSON", "QRIS"],
        url: "/api-docs",
        internal: true,
        cta: "Open API Docs",
      },
      {
        index: "07",
        title: "Content Analytics Platform",
        summary: "A web SaaS for content analytics to monitor post performance across platforms.",
        bullets: [
          "Content analytics dashboard: views, engagement, likes, comments across platforms.",
          "Track content performance as the basis for measurable organic strategy.",
        ],
        stack: ["Web App", "Analytics", "SaaS"],
        url: "https://demo.kasihkreasi.web.id/login",
        cta: "View Demo",
        sourceUrl: "https://github.com/siinmedia/analisakonten",
        sourceLabel: "Source",
      },
    ],
    hardskills: [
      "PHP",
      "HTML & CSS",
      "JavaScript",
      "CRM Development",
      "Internal Systems",
      "Database Management",
      "API & System Integration",
      "Troubleshooting & Maintenance",
    ],
    marketingSkills: [
      "Social Media Management",
      "Content Planning",
      "Content Strategy",
      "Copywriting",
      "Trend Research",
      "Social Media Analytics",
      "Organic Growth Strategy",
    ],
    softskills: [
      "Business Needs Analysis",
      "Problem Solving",
      "System Analysis",
      "Project Management",
      "Business Process Analysis",
    ],
  },
} as const;
