export type Lang = "id" | "en";

export const content = {
  id: {
    langLabel: "ID",
    role: "Web Developer Portfolio",
    heroKicker: "Web Developer & Digital Marketing Specialist",
    heroLine: "Developer yang memahami bisnis, marketing, dan kebutuhan pengguna.",
    seeMore: "Lihat Selengkapnya",
    heroStats: [
      { value: "4+", label: "Tahun Pengalaman" },
      { value: "6", label: "Proyek Kerjaan" },
      { value: "14", label: "Proyek Pribadi" },
      { value: "13", label: "Brand F&B" },
    ],
    tags: [
      "#Web_Development",
      "#PHP",
      "#CRM",
      "#Sistem_Internal",
      "#Landing_Page",
      "#API_Integration",
      "#Digital_Marketing",
      "#Content_Strategy",
      "#Social_Media",
      "#Copywriting",
    ],
    nav: { about: "Tentang", resume: "Resume", work: "Proyek" },
    hello: "Halo,",
    myName: ["Nama saya", "Angger"],
    photoCaption:
      "Dari strategi konten ke sistem yang benar-benar dipakai — solusi digital yang efektif untuk kebutuhan bisnis.",
    introduction: "Perkenalan",
    introTitle: "Web Developer & Digital Marketing Specialist",
    introBody: [
      "Profesional di bidang Web Development dan Digital Marketing dengan pengalaman dalam pengembangan sistem berbasis web, CRM, sistem internal perusahaan, integrasi antarplatform, serta pengelolaan media sosial dan strategi konten.",
      "Berpengalaman mengembangkan solusi digital untuk mendukung kebutuhan operasional dan bisnis perusahaan, sekaligus memiliki pengalaman dalam perencanaan konten, riset tren, copywriting, analisis performa, dan strategi pertumbuhan media sosial.",
    ],
    getInTouch: "Hubungi Saya",
    getInTouchBody:
      "Punya proyek, lowongan, atau sekadar mau ngobrol? Saya fast response di semua channel.",
    contactEmailCta: "Kirim Email",
    contactWhatsappCta: "Fast Response",
    contact: {
      email: "anggerajiprayogokusuma@gmail.com",
      emailLabel: "Email",
      linkedin: "anggeraji",
      linkedinLabel: "LinkedIn",
      linkedinUrl: "https://www.linkedin.com/in/anggeraji",
      github: "siinmedia",
      githubLabel: "GitHub",
      githubUrl: "https://github.com/siinmedia",
      whatsapp: "6285155145788",
      whatsappLabel: "WhatsApp",
      whatsappUrl: "https://wa.me/6285155145788",
      city: "Jepara",
    },
    support: {
      kicker: "Support",
      title: "Dukung Karya",
      subtitle:
        "Dukung pengembangan sistem dan karya digital yang saya buat. Pilih nominal, scan QRIS, dan traktir kopi.",
      label: "Pilih Nominal",
      amounts: [10000, 20000, 50000, 100000],
      customPlaceholder: "Nominal lain (Rp)",
      generate: "Buat QRIS",
      generating: "Membuat QRIS…",
      successTitle: "QRIS siap di-scan",
      copyQris: "Salin Kode",
      copied: "Tersalin!",
      note: "Scan pakai aplikasi e-wallet atau m-banking apa pun.",
      notConfigured:
        "QRIS statis belum diisi — buka src/lib/qris-config.ts lalu ganti QRIS_STATIC dengan kode QRIS kamu.",
      errorPrefix: "Gagal membuat QRIS",
    },
    experience: "Pengalaman Kerja",
    expertise: "Keahlian",
    expertiseBody:
      "Web Development, CRM, Sistem Internal, API & System Integration, Digital Marketing, Content Strategy, Social Media Management",
    hardskill: "Hardskill",
    marketing: "Digital Marketing",
    softskill: "Softskill",
    education: "Pendidikan",
    graduated: "Lulus 2024",
    school: "SMK Negeri 1 Kudus",
    schoolCity: "Kudus, Jawa Tengah",
    extra: "Informasi Tambahan",
    languagesLabel: "Bahasa",
    languagesValue: "Bahasa Indonesia · Bahasa Inggris",
    focusLabel: "Fokus",
    focusValue:
      "Web Development · Programming · CRM · Digital Marketing · Social Media · Content Strategy",
    workTitle: "Proyek Terpilih",
    workSubtitle: "Sistem dan produk digital yang dikembangkan untuk kebutuhan bisnis nyata.",
    present: "Sekarang",
    jobs: [
      {
        period: "Des 2025 — Sekarang",
        role: "PHP Web Developer",
        company: "CV Maha Niaga Artha",
        bullets: [
          "Mengembangkan CRM multi-role untuk pengelolaan pelanggan dan kebutuhan operasional perusahaan.",
          "Membangun sistem internal perusahaan untuk mendukung proses bisnis dan operasional.",
          "Mengembangkan sistem inventaris internal untuk pengelolaan data inventaris.",
          "Mengembangkan landing page untuk kebutuhan perusahaan dan brand.",
          "Melakukan integrasi antarplatform untuk mendukung alur kerja bisnis.",
          "Melakukan troubleshooting, pemeliharaan, dan pengembangan fitur sistem.",
          "Memberikan dukungan teknis dan IT untuk memastikan sistem berjalan dengan baik.",
          "Menganalisis kebutuhan pengguna dan menerjemahkannya menjadi solusi berbasis sistem.",
        ],
        footerLabel: "Sistem",
        footerItems: ["CRM", "Sistem Inventaris Internal", "Sistem Perencanaan Konten"],
      },
      {
        period: "Nov 2022 — Des 2025",
        role: "Social Media Marketing Specialist",
        company: "CV Maha Niaga Artha",
        bullets: [
          "Menyusun strategi dan perencanaan konten untuk berbagai media sosial.",
          "Mengelola kalender konten dan memastikan publikasi berjalan secara terstruktur.",
          "Melakukan riset tren media sosial untuk menghasilkan konten yang relevan dengan audiens.",
          "Membuat copywriting untuk berbagai kebutuhan komunikasi digital.",
          "Menganalisis performa konten dan menggunakan data sebagai dasar pengembangan strategi.",
          "Menjalankan strategi organic growth untuk meningkatkan jangkauan dan engagement.",
          "Mengelola kebutuhan media sosial dari berbagai brand F&B.",
        ],
        footerLabel: "Brand",
        footerItems: [
          "Be Nice Coffee",
          "Esteh Ibukota",
          "Kentang Ganteng",
          "Raja Steak",
          "MyBestea",
        ],
      },
    ],
    projects: [
      {
        index: "01",
        title: "CRM Sistem Manajemen Pelanggan",
        summary: "Sistem manajemen pelanggan multi-role untuk operasional perusahaan.",
        bullets: [
          "Pengembangan CRM dengan sistem akses berdasarkan role pengguna.",
          "Pengelolaan data pelanggan dan kebutuhan operasional.",
          "Pengembangan fitur berdasarkan kebutuhan dan alur bisnis.",
        ],
        stack: ["PHP", "Database", "Role Access"],
      },
      {
        index: "02",
        title: "Sistem Inventaris Internal",
        summary: "Digitalisasi pencatatan dan pengelolaan data inventaris.",
        bullets: [
          "Pengembangan sistem digital untuk pengelolaan inventaris.",
          "Membantu proses pencatatan dan pengelolaan data inventaris perusahaan.",
        ],
        stack: ["PHP", "Database"],
      },
      {
        index: "03",
        title: "Sistem Perencanaan Konten",
        summary: "Alat internal untuk kalender dan alur kerja konten.",
        bullets: [
          "Pengembangan sistem internal untuk membantu proses perencanaan konten.",
          "Pengelolaan kalender dan alur kerja konten secara digital.",
        ],
        stack: ["PHP", "Workflow"],
      },
      {
        index: "04",
        title: "Website & Landing Page",
        summary: "Halaman yang menggabungkan kebutuhan teknis dan tujuan pemasaran.",
        bullets: [
          "Pengembangan website dan landing page untuk kebutuhan bisnis dan pemasaran.",
          "Menggabungkan kebutuhan teknis dengan tujuan pemasaran dan komunikasi brand.",
        ],
        stack: ["HTML & CSS", "JavaScript", "SEO"],
      },
      {
        index: "05",
        title: "TernoAE",
        summary: "Platform ride-hailing lokal dengan sistem booking dan pelacakan real-time.",
        bullets: [
          "Platform ride-hailing lokal dengan booking dan pelacakan real-time.",
          "Web app untuk kebutuhan transportasi dengan fokus pengalaman pengguna.",
        ],
        stack: ["PHP", "Web App", "Transportation"],
        url: "https://ternoae.web.id",
      },
      {
        index: "06",
        title: "QRIS Dynamic API",
        summary: "REST API untuk generate QRIS dinamis dari kode statis dengan nominal yang bisa diatur.",
        bullets: [
          "Endpoint POST JSON — kirim QRIS statis + nominal, terima QRIS dinamis siap scan.",
          "Digunakan untuk integrasi pembayaran, donasi, atau top-up pada sistem internal.",
        ],
        stack: ["REST API", "JSON", "QRIS"],
        url: "/api-docs",
        internal: true,
      },
    ],
    hardskills: [
      "PHP",
      "HTML & CSS",
      "JavaScript",
      "Pengembangan CRM",
      "Sistem Internal",
      "Database Management",
      "API & System Integration",
      "Troubleshooting & Maintenance",
    ],
    marketingSkills: [
      "Social Media Management",
      "Content Planning",
      "Content Strategy",
      "Copywriting",
      "Trend Research",
      "Social Media Analytics",
      "Organic Growth Strategy",
    ],
    softskills: [
      "Analisis Kebutuhan Bisnis",
      "Problem Solving",
      "System Analysis",
      "Project Management",
      "Business Process Analysis",
    ],
  },

  en: {
    langLabel: "EN",
    role: "Web Developer Portfolio",
    heroKicker: "Web Developer & Digital Marketing Specialist",
    heroLine: "A developer who understands business, marketing, and user needs.",
    seeMore: "See More",
    heroStats: [
      { value: "4+", label: "Years Experience" },
      { value: "6", label: "Work Projects" },
      { value: "14", label: "Personal Projects" },
      { value: "13", label: "F&B Brands" },
    ],
    tags: [
      "#Web_Development",
      "#PHP",
      "#CRM",
      "#Internal_Systems",
      "#Landing_Page",
      "#API_Integration",
      "#Digital_Marketing",
      "#Content_Strategy",
      "#Social_Media",
      "#Copywriting",
    ],
    nav: { about: "About me", resume: "Resume", work: "Work" },
    hello: "Hello,",
    myName: ["My name", "is Angger"],
    photoCaption:
      "From content strategy to systems people actually use — effective digital solutions for real business needs.",
    introduction: "Introduction",
    introTitle: "Web Developer & Digital Marketing Specialist",
    introBody: [
      "A professional in Web Development and Digital Marketing with experience building web-based systems, CRM, internal company systems, cross-platform integrations, as well as social media management and content strategy.",
      "Experienced in developing digital solutions that support business and operational needs, combined with a background in content planning, trend research, copywriting, performance analysis, and social media growth strategy.",
    ],
    getInTouch: "Get In Touch",
    getInTouchBody:
      "Have a project, a vacancy, or just want to chat? I reply fast on all channels.",
    contactEmailCta: "Send Email",
    contactWhatsappCta: "Fast Response",
    contact: {
      email: "anggerajiprayogokusuma@gmail.com",
      emailLabel: "Email",
      linkedin: "anggeraji",
      linkedinLabel: "LinkedIn",
      linkedinUrl: "https://www.linkedin.com/in/anggeraji",
      github: "siinmedia",
      githubLabel: "GitHub",
      githubUrl: "https://github.com/siinmedia",
      whatsapp: "6285155145788",
      whatsappLabel: "WhatsApp",
      whatsappUrl: "https://wa.me/6285155145788",
      city: "Jepara",
    },
    support: {
      kicker: "Support",
      title: "Support My Work",
      subtitle:
        "Support the systems and digital work I build. Pick an amount, scan the QRIS, and buy me a coffee.",
      label: "Choose Amount",
      amounts: [10000, 20000, 50000, 100000],
      customPlaceholder: "Other amount (IDR)",
      generate: "Generate QRIS",
      generating: "Generating QRIS…",
      successTitle: "QRIS ready to scan",
      copyQris: "Copy Code",
      copied: "Copied!",
      note: "Scan with any e-wallet or mobile banking app.",
      notConfigured:
        "QRIS static is not set — open src/lib/qris-config.ts and replace QRIS_STATIC with your QRIS code.",
      errorPrefix: "Failed to generate QRIS",
    },
    experience: "Experience",
    expertise: "Expertise",
    expertiseBody:
      "Web Development, CRM, Internal Systems, API & System Integration, Digital Marketing, Content Strategy, Social Media Management",
    hardskill: "Hard Skills",
    marketing: "Digital Marketing",
    softskill: "Soft Skills",
    education: "Education",
    graduated: "Class of 2024",
    school: "SMK Negeri 1 Kudus",
    schoolCity: "Kudus, Central Java",
    extra: "Additional Information",
    languagesLabel: "Languages",
    languagesValue: "Indonesian · English",
    focusLabel: "Focus",
    focusValue:
      "Web Development · Programming · CRM · Digital Marketing · Social Media · Content Strategy",
    workTitle: "Selected Work",
    workSubtitle: "Systems and digital products built for real business needs.",
    present: "Present",
    jobs: [
      {
        period: "Dec 2025 — Present",
        role: "PHP Web Developer",
        company: "CV Maha Niaga Artha",
        bullets: [
          "Built a multi-role CRM for customer management and company operations.",
          "Developed internal company systems supporting business and operational processes.",
          "Built an internal inventory system for managing inventory data.",
          "Developed landing pages for company and brand needs.",
          "Implemented cross-platform integrations to support business workflows.",
          "Handled troubleshooting, maintenance, and ongoing feature development.",
          "Provided technical and IT support to keep systems running reliably.",
          "Analysed user needs and translated them into system-based solutions.",
        ],
        footerLabel: "Systems",
        footerItems: ["CRM", "Internal Inventory System", "Content Planning System"],
      },
      {
        period: "Nov 2022 — Dec 2025",
        role: "Social Media Marketing Specialist",
        company: "CV Maha Niaga Artha",
        bullets: [
          "Developed content strategy and planning across social media channels.",
          "Managed the content calendar and kept publishing consistent and structured.",
          "Researched social media trends to produce content relevant to the audience.",
          "Wrote copy for a wide range of digital communication needs.",
          "Analysed content performance and used data to shape strategy.",
          "Ran organic growth strategies to increase reach and engagement.",
          "Managed social media for multiple F&B brands.",
        ],
        footerLabel: "Brands",
        footerItems: [
          "Be Nice Coffee",
          "Esteh Ibukota",
          "Kentang Ganteng",
          "Raja Steak",
          "MyBestea",
        ],
      },
    ],
    projects: [
      {
        index: "01",
        title: "CRM Customer Management System",
        summary: "A multi-role customer management system for company operations.",
        bullets: [
          "Built a CRM with access control based on user roles.",
          "Managed customer data and operational requirements.",
          "Developed features around real business needs and workflows.",
        ],
        stack: ["PHP", "Database", "Role Access"],
      },
      {
        index: "02",
        title: "Internal Inventory System",
        summary: "Digitised inventory recording and data management.",
        bullets: [
          "Built a digital system for inventory management.",
          "Supported recording and management of company inventory data.",
        ],
        stack: ["PHP", "Database"],
      },
      {
        index: "03",
        title: "Content Planning System",
        summary: "An internal tool for content calendars and workflows.",
        bullets: [
          "Built an internal system to support the content planning process.",
          "Managed content calendars and workflows digitally.",
        ],
        stack: ["PHP", "Workflow"],
      },
      {
        index: "04",
        title: "Website & Landing Page",
        summary: "Pages that combine technical needs with marketing goals.",
        bullets: [
          "Developed websites and landing pages for business and marketing needs.",
          "Combined technical requirements with marketing and brand communication goals.",
        ],
        stack: ["HTML & CSS", "JavaScript", "SEO"],
      },
      {
        index: "05",
        title: "TernoAE",
        summary: "Local ride-hailing platform with real-time booking and tracking system.",
        bullets: [
          "Local ride-hailing platform with real-time booking and tracking.",
          "Web app built for transportation, focused on user experience.",
        ],
        stack: ["PHP", "Web App", "Transportation"],
        url: "https://ternoae.web.id",
      },
      {
        index: "06",
        title: "QRIS Dynamic API",
        summary: "REST API to generate dynamic QRIS from a static code with customizable amount.",
        bullets: [
          "JSON POST endpoint — send static QRIS + amount, get a ready-to-scan dynamic QRIS.",
          "Used for payment, donation, or top-up integrations across internal systems.",
        ],
        stack: ["REST API", "JSON", "QRIS"],
        url: "/api-docs",
        internal: true,
      },
    ],
    hardskills: [
      "PHP",
      "HTML & CSS",
      "JavaScript",
      "CRM Development",
      "Internal Systems",
      "Database Management",
      "API & System Integration",
      "Troubleshooting & Maintenance",
    ],
    marketingSkills: [
      "Social Media Management",
      "Content Planning",
      "Content Strategy",
      "Copywriting",
      "Trend Research",
      "Social Media Analytics",
      "Organic Growth Strategy",
    ],
    softskills: [
      "Business Needs Analysis",
      "Problem Solving",
      "System Analysis",
      "Project Management",
      "Business Process Analysis",
    ],
  },
} as const;
